version: '3.6'

services:
  hello-dummy:
    build: .
    image: ghcr.io/polouis/dummy-deploy
    ports:
      - 80
    networks:
      - ubuntu_default

networks:
  ubuntu_default:
    external: true
