name: Deploy

on:
  workflow_dispatch:

env:
  TARGET_HOST: ssh.polouis.com
  CLIENT_PRIVATE_KEY: ${{ secrets.CLIENT_PRIVATE_KEY }}
  SERVER_PUBLIC_KEY: ${{ secrets.SERVER_PUBLIC_KEY }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
    - name: Checkout and build
      run: docker-compose build

    - name: Prepare ssh configuration
      run: |
        mkdir -p ~/.ssh
        chmod 0700 ~/.ssh
        echo "${{ env.SERVER_PUBLIC_KEY }}" >> ~/.ssh/known_hosts
        echo "${{ env.CLIENT_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
        sudo chmod 600 ~/.ssh/id_ed25519

    - name: Create docker context
      run: |
        docker context create --docker host=ssh://deploy@ssh.polouis.com --description="OVH Server" ovh-server
        docker context use ovh-server
#        docker info
  
    - name: Restart container
      run: docker-compose up --no-deps -d hello-dummy
