name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


env:
  TARGET_HOST: ssh.polouis.com
  OVH_KEY: ${{ secrets.OVH_KEY }}
  OVH_KEYSCAN: ${{ secrets.OVH_KEYSCAN }}
  COMPOSE_PARAMIKO_SSH: 1

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Prepare ssh configuration
      run: |
        mkdir -p ~/.ssh
        chmod 0700 ~/.ssh
        echo "$OVH_KEYSCAN" >> ~/.ssh/known_hosts
        echo "$OVH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        sudo chmod 600 ~/.ssh/id_rsa

    - name: Create docker context
      run: |
        docker context create --docker host=ssh://deploy@ssh.polouis.com --description="OVH Server" ovh-server
        docker context use ovh-server
        docker info

    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker-compose build hello

    - name: Update and run
      run: docker compose up --no-deps -d hello
