name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  TARGET_HOST: ssh.polouis.com
  CLIENT_PRIVATE_KEY: ${{ secrets.CLIENT_PRIVATE_KEY }}
  SERVER_PUBLIC_KEY: ${{ secrets.SERVER_PUBLIC_KEY }}
#  COMPOSE_PARAMIKO_SSH: 1

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Prepare ssh configuration
      run: |
        mkdir -p ~/.ssh
        chmod 0700 ~/.ssh
        echo "$SERVER_PUBLIC_KEY" >> ~/.ssh/known_hosts
        echo $CLIENT_PRIVATE_KEY | tr -d '\r' > ~/.ssh/id_ed25519
        sudo chmod 600 ~/.ssh/id_ed25519

    - uses: actions/checkout@v3
    - name: Create docker context
      run: |
        docker context create --docker host=ssh://deploy@ssh.polouis.com --description="OVH Server" ovh-server
        docker context use ovh-server
        docker info
        docker-compose build hello
        docker compose up --no-deps -d hello
